name: Deploy

on:
  push:
    branches: [ master ]
concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: gemeindetag.mennoniten.de
      url: gemeindetag.mennoniten.de
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build Files
        run: npm run build

      - name: Deploy
        uses: fabian-kaegy-org/ftp-deployer@v1.3.2
        with:
          sftp: false
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          local_folder: './'
          remote_folder: '~/html/wordpress/wp-content/themes/gemeindetag/'
          cleanup: true
          exclude: '["node_modules/, node_modules/**, node_modules/**/.*, .git/**, phpcs.xml, package.json, package-lock.json, assets/**, composer.json, composer.lock"]'
        
