name: Deploy

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: gemeindetag.mennoniten.de
      url: gemeindetag.mennoniten.de
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Files
        run: npm run build

      - name: ssh deploy
        uses: hengkx/ssh-deploy@v1.0.1
        with:
          HOST: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PASSWORD: ${{ secrets.SERVER_SSH_PASSWORD }}
          SOURCE: .
          TARGET: /html/wordpress/wp-content/themes/gemeindetag/
        
