name: Deploy

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: gemeindetag.mennoniten.de
      url: gemeindetag.mennoniten.de
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Files
        run: npm run build

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.6
        with:
          # Private Key
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PASSWORD }}
          # Remote host
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          # Remote user
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          # Target directory in the format of `sites/${domain}/files/wp-content/...`
          TARGET: html/wordpress/wp-content/themes/gemeindetag/
          # An array of folder to exclude
          EXCLUDE: node_modules, .git
